booksmanagement/booksapp/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import BookList, BookDetail, BookCreate, BookDelete, BookUpdate

urlpatterns = [
    path('admin/', admin.site.urls),
    path('list/', BookList.as_view(), name='list'),
    path('detail/<int:pk>', BookDetail.as_view(), name='detail'),
    path('add/', BookCreate.as_view(), name='add'),
    path('delete/<int:pk>', BookDelete.as_view(), name='delete'),
    path('update/<int:pk>', BookUpdate.as_view(), name='update'),
]

booksmanagement/booksmanagement/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('booksapp.urls')),
    
    ]

booksmanagement/booksapp/models.py
from django.db import models
from django.utils import timezone

# Create your models here.



class BooksList(models.Model):
    STATUS_CHOICES = [
        ('unread', '未読'),
        ('read', '既読'),
    ]
    title = models.CharField(max_length=100)
    memo = models.TextField()
    read = models.CharField(
        max_length=50,
        choices=STATUS_CHOICES,
        default='unread'    
    )
    p_date = models.DateField(default=timezone.now)

    def __str__(self):
        return self.title

booksmanagement/booksapp/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from .models import BooksList
from django.urls import reverse_lazy

# Create your views here.

class BookList(ListView):
    template_name = 'list.html'
    model = BooksList

class BookDetail(DetailView):
    template_name = 'detail.html'
    model = BooksList

class BookCreate(CreateView):
    template_name='add.html'
    model = BooksList
    fields = ('title', 'memo', 'read', 'p_date')
    success_url = reverse_lazy('list')

class BookDelete(DeleteView):
    template_name = 'delete.html'
    model = BooksList
    success_url = reverse_lazy('list')

class BookUpdate(UpdateView):
    template_name = 'update.html'
    model = BooksList
    fields = ('title', 'memo', 'read', 'p_date')
    success_url = reverse_lazy('list')

booksmanagement/templates/add.html
{% extends 'base.html' %}

{% block content %}
<h1 class="display-10">書籍追加ページ</h1>
<div class="container">
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <form action='' method='POST'>{% csrf_token %}
                
                <p><label for="id_title">・書籍タイトル : </label> <input type="text" name="title" maxlength="100" required id="id_title"></p>
                <p><label for="id_memo">・メモ : </label> <textarea name="memo" cols="40" rows="10" required id="id_memo"></textarea></p>
                <p><label for="id_read">・状態 : </label> <select name="read" id="id_read">
                <option value="unread" selected>未読</option>
                <option value="read">既読</option>
                </select></p>
                <p>・購入日 : {{ form.p_date }}</p>

                <input type='submit' value='追加'>
            </form>
        </div>
    </div>
</div>
{% endblock content %}
{{ form.as_p }}

booksmanagement/templates/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>

    {% block header %}
    {% endblock header %}

    {% block content %}
    {% endblock content %}

    </body>
</html>

booksmanagement/templates/delete.html
{% extends 'base.html' %}

{% block content %}
<h1 class="display-10">書籍削除ページ</h1>

<div class="container">
    <div class="container">
        <div class="alert alert-danger" role="alert">
            <div class="container"> 
                <div class="alert alert-{{ item.read }}" role="alert">
                    <p>・書籍タイトル : {{ object.title }}</p>
                    <p>・メモ : {{ object.memo }}</p>
                    <p>・状態 : {{ object.read }}</p>
                    <p>・購入日 : {{ object.p_date }}</p>
                </div>
            </div>
        </div>            
    </div>
<form action='' method='POST'>{% csrf_token %}
    <input type='submit' value='削除'>
</form>
{% endblock content %}

<div class="alert alert-success" role="alert">
    {{ object.title }}
 </div>
 <div class="alert alert-success" role="alert">
     {{ object.memo }}
 </div>

booksmanagement/templates/detail.html
{% extends 'base.html' %}

{% block header %}
<h1 class="display-10">書籍詳細ページ</h1>
{% endblock %}

{% block content %}
<div class="container">
    <div class="alert alert-success" role="alert">
        書籍タイトル : {{ object.title }}
    </div>
    <div class="alert alert-success" role="alert">
        メモ : {{ object.memo }}
    </div>
    <div class="alert alert-success" role="alert">
        状態 : {{ object.read }}
    </div>
    <div class="alert alert-success" role="alert">
        購入日 : {{ object.p_date | date:"o/n/j" }}
    </div>

    <button class="btn btn-primary" onclick="history.back(-1)">戻る</button>

</div>
{% endblock content %}

booksmanagement/templates/list.html
{% extends 'base.html' %}

{% block header %}
    
<h1 class="display-4">書籍一覧ページ</h1>

{% endblock %}

{% block content %}
<div class="container">
    <a href="{% url 'add' %}" class="btn btn-secondary mb-2" tabindex="-1" role="button" aria-disabled="true">追加</a>
    {% for item in object_list %}
    <div class="container">
            <div class="container"> 
                <div class="alert alert-info" role="alert">
                    <p>・書籍タイトル : {{ item.title }}</p>
                    <p>・購入日 : {{ item.p_date | date:"o/n/j" }}</p>
                    <a href="{% url 'detail' item.pk %}" class="btn btn-primary btn-lg" tabindex="-1" role="button" aria-disabled="true">詳細</a>
                    <a href="{% url 'delete' item.pk %}" class="btn btn-success btn-lg" tabindex="-1" role="button" aria-disabled="true">削除</a>
                    <a href="{% url 'update' item.pk %}" class="btn btn-info btn-lg" tabindex="-1" role="button" aria-disabled="true">更新</a>
                </div>
            </div>
    </div>

    {% endfor %}
</div>
{% endblock content %}

booksmanagement/templates/update.html
{% extends 'base.html' %}

{% block content %}

<h1 class="display-10">書籍更新ページ</h1>
<div class="container">
    <div class="alert alert-warning" role="alert">
        <div class="container">
            <form action='' method='POST'>{% csrf_token %}
               
            <p><label for="id_title">・書籍タイトル : </label> <input type="text" name="title" value="{{ object.title }}" maxlength="100" required id="id_title"></p>
            <p><label for="id_memo">・メモ : </label> <textarea name="memo" cols="40" rows="10" required id="id_memo">{{ object.memo }}</textarea></p>
            <p><label for="id_read">・状態 : </label> <select name="read" id="id_read">
            <option value="unread" selected>未読</option>
            <option value="read">既読</option>
            </select></p>
            <p><label for="id_p_date">・購入日 : 
            </label> <input type="text" name="p_date" value= {{object.p_date | date:"o-n-j"}} required id="id_p_date"><input type="hidden" name="initial-p_date" value={{object.p_date | date:"o-n-j"}} id="initial-id_p_date"></p>
                        
                <input type='submit' value='更新'>
            </form>
        </div>
    </div>
</div>

{% endblock content %}



 {{ form.as_p }}